### ISSUE TITLE
Feat: Create plugin should add a dependabot config to regularly update `grafana-plugin-sdk-go` package

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/plugin-tools#1088]
### Which areas does this feature request relate to

- [x] Create Plugin
- [ ] Sign Plugin
- [ ] Plugin E2E
- [ ] Plugin Meta Extractor
- [ ] Documentation

### Problem

We are adding to plugin repositories dependabot config that checks weekly, if `grafana-plugin-sdk-go` was updated and if so, creates a PR with updated version. This helps with making sure that plugins are up to date with new sdk, which currently is an issue.

Related to https://github.com/grafana/data-sources/issues/63 

### Solution

Example of the dependabot config: https://github.com/grafana/grafana-infinity-datasource/blob/main/.github/dependabot.yml 

```
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      # Keep the sdk modules up-to-date
      - dependency-name: "github.com/grafana/grafana-plugin-sdk-go"
        dependency-type: "all"
    commit-message:
      prefix: "Upgrade grafana-plugin-sdk-go "
      include: "scope"
```

While here I am focusing on plugin-sdk, we could think further if there are other packages/dependencies, that we would like to regularly update.
