### ISSUE TITLE
Bug: When migrating an old plugin, docker-compose.yml shortens names

### ISSUE THREAD

**Issue by iwysiu** [grafana/plugin-tools#166]
### Package Name

create-plugin

### What happened?

When migrating a datasource plugin from grafana/toolkit, the generated `docker-compose.yml` sets the name incorrectly.

An example, is that for the athena datasource it generated the container name as `rafanaabs-mazonthena-datasource` and the volume as `./dist:/var/lib/grafana/plugins/rafanaabs-mazonthena-datasource`

I assume it has something to do with how `pluginId` is interpreted.

### What you expected to happen

I would expect the container name to be `grafana-athena-datasource` and the volume to be `./dist:/var/lib/grafana/plugins/grafana-athena-datasource`. This is because the plugin validator expects a `<username>-<plugin>-<type>` format without extra `-`, but `grafana-labs-amazon-athena-datasource` is also acceptable.

### How to reproduce it (as minimally and precisely as possible)

1. Clone the https://github.com/grafana/athena-datasource repository
2. Run `npx @grafana/create-plugin migrate` in `athena-datasource`
3. Check the `docker-compose.yml` file

### Environment

```shell
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
    Memory: 122.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Safari: 16.1
  npmPackages:
    @grafana/aws-sdk: 0.0.37 => 0.0.38 
    @grafana/data: 8.2.1 => 8.5.10 
    @grafana/e2e: 8.2.1 => 8.5.10 
    @grafana/e2e-selectors: 8.2.1 => 8.5.10 
    @grafana/eslint-config: ^2.5.0 => 2.5.2 
    @grafana/experimental: ^0.0.2-canary.39 => 0.0.2-canary.39 
    @grafana/runtime: 8.2.1 => 8.5.10 
    @grafana/tsconfig: ^1.2.0-rc1 => 1.2.0-rc1 
    @grafana/ui: 8.2.1 => 8.5.10
```

**Comment by jackw** [comment]
Thanks for reporting this however I believe this bug was fixed in #128.

I cloned the repo and did `git co d9b1bfa9f1ff9b65efd5bec141279cc8160a9d87` to go back to a commit before create-plugin migration was performed and ran `npx @grafana/create-plugin migrate` and the resulting docker-compose.yaml looks like:

```yaml
version: '3.0'

services:
  grafana:
    container_name: 'grafana-athena-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.2.5}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-athena-datasource
      - ./provisioning:/etc/grafana/provisioning
```

Closing as I believe the issue has been resolved.
